git:
  depth: 1

sudo: false

language: node_js

node_js:
- 6.11.1

cache:
  yarn: true

before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.0.2

install:
    - yarn

script:
    - yarn run lint
    - yarn run flow
